#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
BUILDER="$ROOT_DIR/build-openwrt-custom-image-linux.sh"
WORKFLOW="$ROOT_DIR/.github/workflows/release-vpn-panel.yml"
CANDIDATE_WORKFLOW="$ROOT_DIR/.github/workflows/validate-router-ui-candidate.yml"
DIAGNOSTIC_WORKFLOW="$ROOT_DIR/.github/workflows/diagnose-router-ui-vm.yml"
BASELINE_WORKFLOW="$ROOT_DIR/.github/workflows/build-router-ui-legacy-baselines.yml"
VM_GATE="$ROOT_DIR/tests/vm/router-ui-vm-gate.sh"
VM_GUEST="$ROOT_DIR/tests/vm/router-ui-vm-guest.sh"
VM_FIXTURE="$ROOT_DIR/tests/vm/fixtures/legacy-nonsecret"
STORAGE_DERIVER="$ROOT_DIR/scripts/derive-rd23-storage-layout.sh"
STORAGE_GEOMETRY="$ROOT_DIR/release/rd23-storage-geometry.json"
X86_EXTENT_PATCHER="$ROOT_DIR/scripts/patch-openwrt-x86-writable-extent.sh"
RELEASE_STAGER="$ROOT_DIR/scripts/stage-router-release.sh"
RELEASE_VALIDATOR="$ROOT_DIR/scripts/validate-staged-release.sh"

grep -q 'PROJECT_PACKAGE_DIR' "$BUILDER"
grep -q 'PROJECT_PACKAGE_MANIFEST' "$BUILDER"
grep -q 'Missing prebuilt project package' "$BUILDER"
grep -q 'ImageBuilder contains stale project IPKs' "$BUILDER"
grep -q 'rm -rf "$TARGET_OUT"' "$BUILDER"
grep -q 'project-ipk-sha256sums' "$BUILDER"
grep -q 'router-ui-packages.txt' "$BUILDER"
grep -q 'image-provenance.json' "$BUILDER"
grep -q 'INSTALLED_PACKAGE_SET_DIR' "$BUILDER"
grep -q 'project-payload-sha256sums' "$BUILDER"
grep -q 'overlay-files.txt' "$BUILDER"
grep -q 'profile-info.txt' "$BUILDER"
grep -q 'CONFIG_TARGET_ROOTFS_EXT4FS is not set' "$BUILDER"
grep -q 'squashfs-combined.img.gz' "$BUILDER"
grep -q 'ROOTFS_WRITABLE_KIB' "$BUILDER"
grep -q 'derive-rd23-storage-layout.sh' "$BUILDER"
grep -q 'rd23-storage-geometry.json' "$BUILDER"
grep -q 'IMAGEBUILDER_LOCAL_KEY_DIR' "$BUILDER"
grep -q 'REQUIRE_PINNED_IMAGEBUILDER_KEY' "$BUILDER"
grep -q 'imagebuilder_local_key_fingerprint' "$BUILDER"
grep -Fq '"$IB_DIR/keys/$IMAGEBUILDER_LOCAL_KEY_FINGERPRINT"' "$BUILDER"
grep -q "name '\\*.bom.cdx.json'" "$BUILDER"
grep -q '.metadata.timestamp = $timestamp' "$BUILDER"
! grep -Fq 'cp "$BUILD_LOG" "$PROFILE_ARTIFACT_DIR/build.log"' "$BUILDER"
grep -q 'REQUIRE_PINNED_IMAGEBUILDER_KEY' "$RELEASE_VALIDATOR"
grep -q 'ROOTFS_SIZE_SPEC' "$X86_EXTENT_PATCHER"
grep -q 'rootfs_data_volume_kib' "$STORAGE_DERIVER"
jq -e '.openwrt.version == "24.10.5" and
  .profiles["rd23-stock"].ubi_partition_bytes == 81788928 and
  .profiles["rd23-ubootmod"].ubi_partition_bytes == 117440512 and
  (.profiles["rd23-ubootmod"].fixed_volumes | length == 2)' \
  "$STORAGE_GEOMETRY" >/dev/null
grep -q 'rm -f "$pkg_dir/Packages" "$pkg_dir/Packages.gz" "$pkg_dir/Packages.sig"' "$BUILDER"
! grep -q 'ipkg-make-index.sh packages' "$BUILDER"
grep -q 'UPDATER_PROTOCOL' "$ROOT_DIR/scripts/build-openwrt-ipks.sh"
! grep -q 'build-openwrt-ipks.sh' "$BUILDER"
grep -q '! -name SHA256SUMS' "$ROOT_DIR/scripts/stage-installed-package-set.sh"
grep -q 'sha256sum -c SHA256SUMS' "$ROOT_DIR/scripts/stage-installed-package-set.sh"

grep -q 'uses: actions/download-artifact@v4' "$WORKFLOW"
grep -q 'name: canonical-router-ui-ipks' "$WORKFLOW"
grep -q 'PROJECT_PACKAGE_DIR:' "$WORKFLOW"
grep -q 'REQUIRE_IMAGES: "1"' "$WORKFLOW"
grep -q 'rd23-stock' "$WORKFLOW"
grep -q 'rd23-ubootmod' "$WORKFLOW"
grep -q 'PROFILE: xiaomi_mi-router-ax3000t$' "$WORKFLOW"
! grep -q 'PROFILE: xiaomi_mi-router-ax3000t-stock' "$WORKFLOW"
grep -q 'x86-64' "$WORKFLOW"
grep -q '^  tagged-vm-shards:' "$WORKFLOW"
grep -q '^  aggregate-tagged-vm-evidence:' "$WORKFLOW"
grep -q 'router-ui-vm-gate.sh' "$WORKFLOW"
grep -q 'download-immutable-actions-artifact.sh candidate' "$WORKFLOW"
grep -q '^      candidate_artifact_id:' "$WORKFLOW"
grep -q '^      candidate_artifact_zip_sha256:' "$WORKFLOW"
grep -q '^  x86-image:' "$WORKFLOW"
grep -q 'name: router-image-rd23-stock' "$WORKFLOW"
grep -q 'max-parallel: 2' "$WORKFLOW"
grep -Fq -- "-name '*xiaomi-ax3000t-stock.tar.gz'" "$WORKFLOW"
grep -q 'rd23_storage_layout.rootfs_data_volume_kib' "$WORKFLOW"
! grep -Eq 'writable_budget_kib: (54436|61440|76800|87040)' "$WORKFLOW"

grep -q 'source_sha:' "$CANDIDATE_WORKFLOW"
grep -q 'environment: router-ui-production-signing' "$CANDIDATE_WORKFLOW"
grep -q 'ROOTFS_PARTSIZE:' "$CANDIDATE_WORKFLOW"
grep -q 'WRITABLE_BUDGET_KIB:' "$CANDIDATE_WORKFLOW"
grep -q 'router-ui-vm-gate.sh' "$CANDIDATE_WORKFLOW"
grep -q 'pretag-router-ui-candidate-' "$CANDIDATE_WORKFLOW"
grep -q '^  x86-image:' "$CANDIDATE_WORKFLOW"
grep -q 'name: candidate-router-image-rd23-stock' "$CANDIDATE_WORKFLOW"
grep -q 'max-parallel: 2' "$CANDIDATE_WORKFLOW"
grep -q '.storage_profiles\["rd23-stock"\].writable_backing_kib' "$CANDIDATE_WORKFLOW"
! grep -Eq 'writable_budget_kib: (54436|61440|76800|87040)' "$CANDIDATE_WORKFLOW"
grep -q '^  workflow_dispatch:' "$DIAGNOSTIC_WORKFLOW"
! grep -q '^  push:' "$DIAGNOSTIC_WORKFLOW"
grep -q '^      candidate_artifact_id:' "$DIAGNOSTIC_WORKFLOW"
grep -q '^      candidate_artifact_zip_sha256:' "$DIAGNOSTIC_WORKFLOW"
grep -q '^      baseline_pack_artifact_id:' "$DIAGNOSTIC_WORKFLOW"
grep -q '^      baseline_pack_artifact_zip_sha256:' "$DIAGNOSTIC_WORKFLOW"
! grep -q '^      candidate_run_id:' "$DIAGNOSTIC_WORKFLOW"
! grep -q '^      candidate_source_sha:' "$DIAGNOSTIC_WORKFLOW"
grep -q 'download-immutable-actions-artifact.sh candidate' "$DIAGNOSTIC_WORKFLOW"
grep -q 'download-immutable-actions-artifact.sh baseline' "$DIAGNOSTIC_WORKFLOW"
grep -q 'ROUTER_UI_VM_DIAGNOSTIC: "1"' "$DIAGNOSTIC_WORKFLOW"
grep -q 'release_evidence:false' "$DIAGNOSTIC_WORKFLOW"
grep -q 'set -Eeuo pipefail' "$DIAGNOSTIC_WORKFLOW"
grep -q "sed 's#\^./##'" "$DIAGNOSTIC_WORKFLOW"
! grep -q '^    environment:' "$DIAGNOSTIC_WORKFLOW"
! grep -Eq 'ROUTER_UI_USIGN_SECRET_KEY|SIGNING_KEY|build-openwrt-ipks|build-openwrt-custom-image' "$DIAGNOSTIC_WORKFLOW"
! grep -Eq 'gh (release|pr)|git (tag|push)' "$DIAGNOSTIC_WORKFLOW"
! grep -q 'matrix:' "$DIAGNOSTIC_WORKFLOW"
grep -q '^  workflow_dispatch:' "$BASELINE_WORKFLOW"
! grep -q '^  push:' "$BASELINE_WORKFLOW"
! grep -Eq 'ROUTER_UI_USIGN_SECRET_KEY|environment: router-ui-production-signing' "$BASELINE_WORKFLOW"
grep -q "network.lan.proto='dhcp'" "$VM_GATE"
grep -q 'HOST_ORIGIN="https://127.0.0.1:' "$VM_GATE"
grep -q 'host_bin/sha256' "$VM_GATE"
grep -q 'VM base build failed' "$VM_GATE"
grep -q 'umask 022.*make -C.*image' "$VM_GATE"
grep -q 'extract_openwrt_gzip_image' "$VM_GATE"
grep -q 'decompression OK, trailing garbage ignored' "$VM_GATE"
grep -q "awk 'NF { count++ } END { print count + 0 }'" "$VM_GATE"
grep -q 'qemu-img info --output=json' "$VM_GATE"
grep -q '^  qemu-system-x86_64 ' "$VM_GATE"
grep -q 'file=\$disk,if=ide,format=qcow2' "$VM_GATE"
grep -q 'model=e1000' "$VM_GATE"
grep -q 'logfile=\$EVIDENCE_DIR/\$name.serial.log' "$VM_GATE"
! grep -Eq 'if=virtio|virtio-net-pci' "$VM_GATE"
grep -q 'wait_serial_console' "$VM_GATE"
grep -q 'time.sleep(0.003)' "$VM_GATE"
! sed -n '/^wait_ssh()/,/^}/p' "$VM_GATE" | grep -q 'console_bootstrap_key'
grep -q 'chmod 755 "$overlay" "$overlay/etc"' "$VM_GATE"
grep -q "stat -c '%a'" "$VM_GATE"
grep -q 'unsafe ImageBuilder overlay directory mode' "$VM_GATE"
grep -q 'serial harness attempted to overlap project VMs' "$VM_GATE"
grep -q 'kill -0 "$CURRENT_PID"' "$VM_GATE"
grep -q 'kill -9 "$CURRENT_PID"' "$VM_GATE"
grep -q 'wait "$CURRENT_PID"' "$VM_GATE"
grep -q 'trap cleanup EXIT' "$VM_GATE"
grep -q "trap 'exit 130' INT" "$VM_GATE"
grep -q "trap 'exit 143' TERM" "$VM_GATE"
grep -q 'vm_execution_mode:"strictly-serial-exact-child-pid"' "$VM_GATE"
! test -e "$ROOT_DIR/tests/vm/qemu-guard.sh"
! grep -Eq 'pgrep|ps -eo|flock|semaphore|third-vm|MAX_RUNNING|maximum_simultaneous_vms' "$VM_GATE"
grep -q '/proc/mounts' "$VM_GUEST"
grep -q '/sys/class/block/' "$VM_GUEST"
grep -q 'overlay_backing_kib' "$VM_GUEST"
grep -q 'install_non_secret_test_profile' "$VM_GUEST"
grep -q "P_HOST='192.0.2.1'" "$VM_FIXTURE/profile.conf"
grep -q 'domain:router-ui-vm.invalid' "$VM_FIXTURE/direct-domains.txt"
grep -q '"private_key_present": false' "$VM_FIXTURE/fixture-contract.json"
! grep -q 'P_PRIVATE_KEY' "$VM_GUEST"
! grep -Eq 'stock-60|uboot-75|uboot-85' "$VM_GATE" "$VM_GUEST"
for archive_reader in "$WORKFLOW" "$VM_GATE" \
  "$STORAGE_DERIVER" "$RELEASE_STAGER"; do
  ! grep -E 'tar .*\| awk .*exit' "$archive_reader"
  grep -Eq 'tar .*\| awk .*![[:alnum:]_]*found.*found=1' "$archive_reader"
done

# The overlay may contain only the root redirect and the signed exact-package
# recovery set. Project application paths remain owned by the canonical IPKs.
overlay_section="$(sed -n '/^rm -rf "$OVERLAY"/,/^PACKAGES=/p' "$BUILDER")"
printf '%s\n' "$overlay_section" | grep -q 'www/index.html'
printf '%s\n' "$overlay_section" | grep -q 'installed-manifest.json'
printf '%s\n' "$overlay_section" | grep -q 'known-good'
! printf '%s\n' "$overlay_section" | grep -Eq 'luci-static|usr/sbin/vpn-ui|usr/share/vpn-ui'

printf 'Image pipeline consumes canonical IPKs and records package identity\n'
